# Generated by Django 4.2.7 on 2023-11-15 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 15, 17, 9, 39, 828337, tzinfo=datetime.timezone.utc)),
        ),
    ]
